# Generated by Django 4.1.4 on 2023-01-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0002_rename_subjects_module_alter_module_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weeks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "modules",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules_set",
                        to="intmain_main_app.module",
                    ),
                ),
            ],
        ),
    ]
