# Generated by Django 4.1.4 on 2023-01-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "intmain_main_app",
            "0004_weeks_created_at_weeks_slug_weeks_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeks",
            name="modules",
        ),
        migrations.AddField(
            model_name="weeks",
            name="modules",
            field=models.ManyToManyField(
                related_name="modules_set", to="intmain_main_app.module"
            ),
        ),
    ]
