# Generated by Django 4.1.4 on 2023-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0005_remove_weeks_modules_weeks_modules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weeks",
            options={"verbose_name": "07. Weeks", "verbose_name_plural": "07. Weeks"},
        ),
        migrations.AddField(
            model_name="weeks",
            name="week_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
