# Generated by Django 4.1.4 on 2023-01-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0006_alter_weeks_options_weeks_week_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name": "02. module", "verbose_name_plural": "02. Module"},
        ),
        migrations.AlterModelOptions(
            name="quizmultiplechoicesquestions",
            options={
                "verbose_name": "06. Quiz Multiple-Choice",
                "verbose_name_plural": "06. Quiz Multiple-Choice",
            },
        ),
        migrations.RenameField(
            model_name="module",
            old_name="subject_description",
            new_name="module_description",
        ),
        migrations.RenameField(
            model_name="module",
            old_name="subject_name",
            new_name="module_name",
        ),
        migrations.AlterField(
            model_name="module",
            name="icon",
            field=models.ImageField(blank=True, default="", upload_to="module_icons"),
        ),
        migrations.CreateModel(
            name="moduleClass",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default=1)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="intmain_main_app.classes",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="intmain_main_app.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "02_2. module Class",
                "verbose_name_plural": "02_2. module Class",
                "ordering": ("classes", "module"),
                "unique_together": {("module", "classes")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="topics",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="topics",
            name="module_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_topics",
                to="intmain_main_app.moduleclass",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="topics",
            unique_together={("module_class", "topic_name")},
        ),
        migrations.RemoveField(
            model_name="topics",
            name="subject_class",
        ),
        migrations.DeleteModel(
            name="SubjectClass",
        ),
    ]
