# Generated by Django 4.1.4 on 2023-01-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0007_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moduleclass",
            options={
                "ordering": ("Weeks", "module"),
                "verbose_name": "02_2. module Class",
                "verbose_name_plural": "02_2. module Class",
            },
        ),
        migrations.AlterModelOptions(
            name="weeks",
            options={"verbose_name": "01. Weeks", "verbose_name_plural": "01. Weeks"},
        ),
        migrations.AlterUniqueTogether(
            name="moduleclass",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="weeks",
            name="done",
        ),
        migrations.RemoveField(
            model_name="weeks",
            name="modules",
        ),
        migrations.RemoveField(
            model_name="weeks",
            name="user",
        ),
        migrations.RemoveField(
            model_name="weeks",
            name="week_name",
        ),
        migrations.AddField(
            model_name="moduleclass",
            name="Weeks",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="intmain_main_app.weeks",
            ),
        ),
        migrations.AddField(
            model_name="weeks",
            name="active_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="weeks",
            name="class_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="weeks",
            name="class_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="weeks",
            name="icon",
            field=models.ImageField(blank=True, default="", upload_to="Weeks_icons"),
        ),
        migrations.AddField(
            model_name="weeks",
            name="order_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="weeks",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="weeks",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="weeks",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name="moduleclass",
            unique_together={("module", "Weeks")},
        ),
        migrations.RemoveField(
            model_name="moduleclass",
            name="classes",
        ),
        migrations.DeleteModel(
            name="Classes",
        ),
    ]
