# Generated by Django 4.1.4 on 2023-01-28 06:46

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0009_alter_weeks_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="content",
            field=mdeditor.fields.MDTextField(null=True),
        ),
    ]
