# Generated by Django 4.1.4 on 2023-01-28 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("intmain_main_app", "0010_notes_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weeks",
            old_name="class_name",
            new_name="week_number",
        ),
        migrations.RemoveField(
            model_name="weeks",
            name="active_status",
        ),
        migrations.AddField(
            model_name="weeks",
            name="status",
            field=models.BooleanField(
                choices=[
                    ("done", "Done"),
                    ("encomplete", "encomplate"),
                    ("in_progress", "In process"),
                    ("reviewed", "reviewed"),
                ],
                default=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="weeks",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
