# Generated by Django 4.1.4 on 2023-01-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0011_rename_class_name_weeks_week_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeks",
            name="status",
            field=models.BooleanField(
                choices=[
                    ("not_start", "No started"),
                    ("done", "Done"),
                    ("encomplete", "encomplate"),
                    ("in_progress", "In process"),
                    ("reviewed", "reviewed"),
                ],
                default="not_start",
                null=True,
            ),
        ),
    ]
