# Generated by Django 4.1.4 on 2023-01-28 07:45

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "intmain_main_app",
            "0013_activity_remove_messages_room_remove_messages_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_start", "No Started"),
                    ("started", "Started"),
                    ("reviewed", "reviewed"),
                    ("done", "Done"),
                    ("incomplete", "Incomplate"),
                ],
                default="draft",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="module_description",
            field=mdeditor.fields.MDTextField(null=True),
        ),
        migrations.AlterField(
            model_name="weeks",
            name="icon",
            field=models.ImageField(blank=True, default="", upload_to="weeks_icons"),
        ),
        migrations.AlterField(
            model_name="weeks",
            name="status",
            field=models.BooleanField(
                choices=[
                    ("not_start", "No Started"),
                    ("started", "Started"),
                    ("reviewed", "reviewed"),
                    ("done", "Done"),
                    ("incomplete", "Incomplate"),
                ],
                default="not_start",
                null=True,
            ),
        ),
    ]
