# Generated by Django 4.1.4 on 2023-01-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0018_rename_moduleenrolemnet_moduleenrollemnet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moduleenrollemnet",
            options={
                "verbose_name": "6: ModuleEnrolemnet",
                "verbose_name_plural": "ModuleEnrolemnets",
            },
        ),
    ]
