# Generated by Django 4.1.4 on 2023-01-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0019_alter_moduleenrollemnet_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weeks",
            old_name="user",
            new_name="author",
        ),
    ]
