# Generated by Django 4.1.4 on 2023-01-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0020_rename_user_weeks_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topics",
            old_name="module_class",
            new_name="module_week",
        ),
        migrations.RenameField(
            model_name="weeks",
            old_name="class_description",
            new_name="week_description",
        ),
        migrations.AlterUniqueTogether(
            name="topics",
            unique_together={("module_week", "topic_name")},
        ),
    ]
