# Generated by Django 4.1.4 on 2023-01-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0021_rename_module_class_topics_module_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeks",
            name="module",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="intmain_main_app.module",
            ),
        ),
        migrations.AlterField(
            model_name="topics",
            name="module_week",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_topics",
                to="intmain_main_app.weeks",
            ),
        ),
        migrations.DeleteModel(
            name="ModuleWeek",
        ),
    ]
