# Generated by Django 4.1.4 on 2023-01-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0022_weeks_module_alter_topics_module_week_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name": "01. module", "verbose_name_plural": "01. Module"},
        ),
        migrations.AlterModelOptions(
            name="weeks",
            options={"verbose_name": "02. Weeks", "verbose_name_plural": "02. Weeks"},
        ),
        migrations.RemoveField(
            model_name="activity",
            name="subtopic",
        ),
        migrations.AddField(
            model_name="activity",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primarysegments_set",
                to="intmain_main_app.topics",
            ),
        ),
        migrations.DeleteModel(
            name="SubTopics",
        ),
    ]
