# Generated by Django 4.1.4 on 2023-01-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0025_alter_activity_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200, null=True)),
            ],
            options={
                "verbose_name": "00. module Category",
                "verbose_name_plural": "00. Module Category",
            },
        ),
        migrations.AddField(
            model_name="module",
            name="model_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="intmain_main_app.modulecategory",
            ),
        ),
    ]
