# Generated by Django 4.1.4 on 2023-01-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0026_modulecategory_module_model_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="topic",
            new_name="topic_id",
        ),
    ]
