# Generated by Django 4.1.4 on 2023-01-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0027_rename_topic_activity_topic_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="topic_id",
            new_name="topic",
        ),
    ]
