# Generated by Django 4.1.4 on 2023-01-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0029_modulecategory_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="module",
            old_name="model_category",
            new_name="module_category",
        ),
    ]
