# Generated by Django 4.1.4 on 2023-01-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0030_rename_model_category_module_module_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="accomplishing_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
