# Generated by Django 4.1.4 on 2023-01-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0031_topics_accomplishing_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topics",
            old_name="accomplishing_time",
            new_name="estmated_accomplishmet_time",
        ),
    ]
