# Generated by Django 4.1.4 on 2023-01-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "intmain_main_app",
            "0032_rename_accomplishing_time_topics_estmated_accomplishmet_time",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="estmated_accomplishmet_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
