# Generated by Django 4.1.4 on 2023-01-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0033_alter_topics_estmated_accomplishmet_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="is_capstone_project",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topics",
            name="is_solo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="topics",
            name="is_week_project",
            field=models.BooleanField(default=False),
        ),
    ]
