# Generated by Django 4.1.4 on 2023-02-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intmain_main_app", "0034_topics_is_capstone_project_topics_is_solo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="Activity",
            new_name="activity",
        ),
    ]
