# Generated by Django 4.1.4 on 2023-02-04 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("intmain_main_app", "0035_rename_activity_activity_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="codeReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_project_url", models.CharField(max_length=400, null=True)),
                ("descrition", models.TextField(max_length=500, null=True)),
                ("have_other_source_of_ref", models.BooleanField(default=False)),
                ("like_it", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_to_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "7: Code reviews",
                "verbose_name_plural": "Code Reviews",
            },
        ),
    ]
