# Generated by Django 4.1.4 on 2023-01-26 15:02

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "career_goal",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=600,
                        verbose_name="Career gooal",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=authentication.models.Profile.image_upload_to,
                    ),
                ),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                ("country", models.CharField(max_length=20, null=True)),
                ("profession", models.CharField(blank=True, max_length=200, null=True)),
                ("about", models.TextField(blank=True, max_length=300, null=True)),
                ("bio", models.TextField(blank=True, max_length=300, null=True)),
                (
                    "facebook_link",
                    models.URLField(blank=True, max_length=400, null=True),
                ),
                (
                    "linkedin_link",
                    models.URLField(blank=True, max_length=400, null=True),
                ),
                (
                    "tweeter_link",
                    models.URLField(blank=True, max_length=400, null=True),
                ),
                ("github_link", models.URLField(blank=True, max_length=400, null=True)),
                (
                    "followers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Profile",
            },
        ),
    ]
