# Generated by Django 4.1.4 on 2023-01-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="description",
        ),
        migrations.AddField(
            model_name="profile",
            name="career_goal",
            field=models.TextField(
                blank=True, default="", max_length=600, verbose_name="Career gooal"
            ),
        ),
    ]
