# Generated by Django 4.1.4 on 2023-01-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_profile_description_profile_career_goal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="location",
            new_name="country",
        ),
    ]
