# Generated by Django 4.1.4 on 2023-01-11 19:01

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_rename_location_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="/static/assets/img/intmain_avatar.png",
                upload_to=authentication.models.Profile.image_upload_to,
            ),
        ),
    ]
